#define ENCODER_RESOLUTION 2

#define TAPPING_TERM 200

#define PERMISSIVE_HOLD

#define CHORDAL_HOLD

#define QUICK_TAP_TERM 0

// #define RETRO_TAPPING

#define FLOW_TAP_TERM 200

//#define MASTER_LEFT

#define RGBLIGHT_DISABLE_KEYCODES
#define RGBLIGHT_DISABLE_ANIMATIONS
#define RGBLIGHT_DISABLE_BREATHING
#define RGBLIGHT_DISABLE_HUE_AND_SATURATION
